name: Update Repositories Table in Readme
on:
  push:
    branches:
    - main
    paths:
      - 'first/repos/**'
jobs:
  do:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
      - name: Update Repositories Table in Readme
        run: python ./scripts/generate_repos_table.py first
